version: "3.9"

services:
  app:
    build: .
    ports:
      - "8085:8086"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: postgres
    ports:
      - 5432:5433






